title: Captain MeoMews
logo: /assets/img/logo.jpg
description: Everything happened is past. Only one thing can be existing is memory.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
